# Generated by Django 6.0.3 on 2026-03-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='marcelo.marq2001@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
